# Diztl Config file

tracker:
  host: "localhost"
  port: "50052"

node:
  port: "50051"

minIndexFiles: 5

# Add paths to directories here to configure share and downloads folders.
# dir:
#   share:
#     - 
#   downloads:
#   app:

# Various timeouts in seconds.
timeout:
  download: 300
  search: 3
  disconnect: 3
  trackerConnect: 5
  nodeConnect: 5
  ping: 2

chunkSize: 524288 #1024*512

logLevel: "info"
